# FastAPI Backend Configuration
# Generated by SOP Integration Manager

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
import uvicorn
import os

app = FastAPI(title="Vibe Marketing Automation Platform API")

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Dashboard endpoint - Fixed version with proper resource management
@app.get("/")
async def get_dashboard():
    """Serve the main dashboard"""
    try:
        with open("dashboard/index.html", "r", encoding="utf-8") as f:
            content = f.read()
        return HTMLResponse(content=content)
    except FileNotFoundError:
        return HTMLResponse(content="<h1>Dashboard not found</h1>", status_code=404)
    except Exception as e:
        return HTMLResponse(content=f"<h1>Error loading dashboard: {str(e)}</h1>", status_code=500)

# Health check endpoint
@app.get("/api/health")
async def health_check():
    return {"status": "healthy", "service": "vibe-marketing-platform"}

# Analytics endpoints
@app.get("/api/analytics/ga")
async def get_google_analytics():
    return {"data": "google_analytics_data"}

@app.get("/api/analytics/wicked")
async def get_wicked_reports():
    return {"data": "wicked_reports_data"}

# MCP endpoints
@app.post("/api/mcp/convert")
async def mcp_convert():
    return {"status": "converted"}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
